
export enum ErrorsEnum {
  UNSUPPORTED_METHOD = 'UNSUPPORTED_METHOD',
  REDIS_UNAVAILABLE = 'REDIS_UNAVAILABLE',
  FORBIDDEN = 'FORBIDDEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  VALIDATION_ERRORS = 'VALIDATION_ERRORS',
  USER_IS_EXIST = 'USER_IS_EXIST',
  PASSWORDS_MIS_MATCH = 'PASSWORDS_MIS_MATCH'
}